[project]
name = "fizzbuzz"
version = "0.1.0"
description = "Plain fizzbuzz"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "ruff>=0.11.13",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = ["E501"]